on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        include:
          - image_tag: 'Sakura-32B-Qwen2beta-v0.9'
            model_url: 'https://huggingface.co/SakuraLLM/Sakura-32B-Qwen2beta-v0.9-GGUF/resolve/main/sakura-32b-qwen2beta-v0.9-iq4xs.gguf?download=true'
          - image_tag: 'Sakura-32B-Qwen2beta-v0.9.1'
            model_url: 'https://huggingface.co/SakuraLLM/Sakura-32B-Qwen2beta-v0.9.1-GGUF/resolve/main/sakura-32b-qwen2beta-v0.9.1-iq4xs.gguf?download=true'
          - image_tag: 'Sakura-32B-Qwen2beta-v0.10pre1'
            model_url: 'https://huggingface.co/SakuraLLM/Sakura-32B-Qwen2beta-v0.10pre1-GGUF/resolve/main/sakura-32b-qwen2beta-v0.10pre1-iq4xs.gguf?download=true'
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          build-mount-path: '/var/lib/docker'
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Restart docker
        run: sudo systemctl restart docker

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          push: true
          build-args: "LLAMA_CPP_MODEL_URL=${{ matrix.model_url }}"
          tags: |
            xddxdd/runpod-llama-cpp:${{ matrix.image_tag }}
            xddxdd/runpod-llama-cpp:${{ matrix.image_tag }}-gh${{ github.run_id }}
